<?php

$plugin = array(
  'title' => t('Homepage Layout'),
  'icon' => 'homepage-layout.png',
  'category' => t('Ask & Start Theme'),
  'theme' => 'homepage-layout',
  'css' => 'homepage.css',
  'regions' => array(
    'top_region' => t('Top Region'),
    'stats_line' => t('Stats Line'),
    'activity_nodes' => t('Node Activities'),
    'activity_comments' => t('Comment Activities'),
    'bottom_left' => t('Bottom Left'),
    'bottom_right' => t('Bottom Right'),
  ),
);
