<?php

$plugin = array(
  'title' => t('Homepage Layout'),
  'icon' => 'homepage-layout.png',
  'category' => t('Ask & Start Theme'),
  'theme' => 'homepage-layout',
  'css' => 'homepage.css',
  'regions' => array(
    'top_region' => t('Top Region'),
    'stats_line' => t('Stats Line'),
    'side_left' => t('Side Left'),
    'side_right' => t('Side Right'),
    'bottom_region' => t('Bottom Region'),
  ),
);
