<?php

/**
 * Implements hook_form_alter().
 */
function ask_core_form_alter(&$form, &$form_state, $form_id) {
//  dsm($form_id);
//  theme_date_time_ago();
}

/**
 * Override the default exposed filters.
 */
function ask_core_form_views_exposed_form_alter(&$form, $form_state) {
  $view = $form_state['view'];

  switch ($view->name) {
    case 'search':
      $form['#action'] = '/search';
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
 function ask_core_form_question_node_form_alter(&$form, &$form_state, $form_id) {
   global $user;
   $form['field_q_location']['#states'] = array(
     'visible' => array(
       array(
         ':input[name="field_q_location_based[und]"]' => array('checked' => TRUE),
       ),
     ),
   );
   if (!in_array('Moderator', $user->roles) && $user->uid != 1) {
     $form['field_fsea_progress']['#access'] = FALSE;
     $form['field_official_progress']['#access'] = FALSE;
   }
 }

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ask_core_form_comment_form_alter(&$form, &$form_state) {
  $form['actions']['submit']['#value'] = t('Submit');
}
