source 'http://rubygems.org'

gem 'sass', '~>3.3'
gem 'compass', '~>1.0'
gem 'breakpoint', '~>2.4'
gem 'singularitygs', '~>1.4'
gem 'toolkit', '~>2.0'
gem 'guard-livereload', '~> 2.4', require: false
gem 'susy'
gem 'listen', '~>2.10.1'
