<?php

$plugin = array(
  'title' => t('Site Template'),
  'icon' => 'site-template.png',
  'category' => t('Ask & Start Theme'),
  'theme' => 'site-template',
  'css' => 'site-template.css',
  'regions' => array(
    'top_left' => t('Top Left'),
    'top_right' => t('Top Right'),
    'branding' => t('Branding'),
    'navigation' => t('Navigation'),
    'main' => t('Main Content'),
    'footer_1' => t('Footer 1'),
    'footer_2' => t('Footer 2'),
    'footer_3' => t('Footer 3'),
    'footer_4' => t('Footer 4'),
    'footer_bottom' => t('Footer Bottom'),
  ),
);
